### ISSUE TITLE
The use of examples

### ISSUE THREAD

**Issue by flymzero** [nlepage/golang-wasm#1]
I look up a lot about wasm (golang) on the Internet, but the content of your warehouse is the most detailed, but I still don't understand o(╥﹏╥)o, where is there a document or introduction about the usage of wasm (golang), thank you.

**Comment by nlepage** [comment]
I'm really really sorry, I just found out about your issue! (I must have missed the notification...)
I hope it's not too late to bring you an answer...

In fact this repository is based on an article I wrote:
[Go 1.11: WebAssembly for the gophers](https://medium.zenika.com/go-1-11-webassembly-for-the-gophers-ae4bb8b1ee03)
I hope this will bring you the answers you are looking for.

I'm going to add the link to the article in the README

**Comment by flymzero** [comment]
thanks very much， it is not late, 😊
